name: merge_queue
on:
  merge_queue:

jobs:
  labeler:
    name: merge_queue
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ merge_queue
        shell: bash
        run: |
          echo "ðŸ“¥ merge_queue"
